### ISSUE TITLE
admin/product.php not properly merged upon installation

### ISSUE THREAD

**Issue by jeking928** [lat9/usu#10]
https://www.zen-cart.com/showthread.php?225052-Call-to-a-member-function-format()-on-null&p=1354681#post1354681

Lines 12-15 are new in 1.5.6 and get replaced when installing USU.

**Comment by lat9** [comment]
Thanks for the 'reminder'.  I'm planning on pulling that plugin-manager/code-update portion of the USU install out in deference to the notifications that have been added to the zen_href_link code.  Once done, USU should be a true plugin, without any core-file modifications.
