### ISSUE TITLE
Canonical link handling

### ISSUE THREAD

**Issue by lat9** [lat9/usu#12]
It looks like, for v3.0.0+, the special handling that _USU_ provides for the canonical link can be removed.  Those links are generated by `/includes/init_includes/init_canonical.php` using the `zen_href_link` function, which is 'hooked' by the _USU_ observer.

I'm guessing (since I'm late to the party) that the special handling was required for older versions of Zen Cart.

**Comment by lat9** [comment]
I'm going to keep the canonical-link handling within `/includes/classes/usu.php` for a bit.  Note that it's currently unused, as the canonical link generation now relies on the base Zen Cart processing in conjunction with other plugins that might be providing their own, special canonical links.

**Comment by qingyangge** [comment]
Canonical link is not work when I open USU

**Comment by lat9** [comment]
You haven't provided sufficient information for me to diagnose what's going on.  It's probably better to report in the USU's Zen Cart support thread: https://www.zen-cart.com/showthread.php?199064

That way, more Zen Cart users have visibility into your request and any correction.

**Comment by lat9** [comment]
No response for the past year; closing.
