### ISSUE TITLE
possible anchor problem...

### ISSUE THREAD

**Issue by proseLA** [lat9/usu#25]
https://github.com/lat9/usu/blob/ca4605881f5b5a554cc926e0c3733b8603b503c3/includes/classes/usu.php#L922

hi cindy,
i am in process of upgrading a clients site, and for whatever reason am updating some of the plugins.  this one has always been a bit of a bear, but with your name now attached to it...

i am currently having a little problem with categories, when i came across the line of code referenced above.   i think that the:

```-c-```

should really be:

```$this->reg_anchors['cPath']```

that way someone can easily change the category anchor in just one place....

**Comment by lat9** [comment]
Agreed.
