### ISSUE TITLE
When I open the USU,Zen-cart some plugin not work!

### ISSUE THREAD

**Issue by qingyangge** [lat9/usu#27]
When I open the USU,Zen-cart some plugin not work!
1.header  Canonical link is hidden (maybe not work)
2.Structured Data Plugin  (which link not work)
3.Dynamic Filter (the plugin not work)

**Comment by lat9** [comment]
As with your update to issue #12, you haven't provided sufficient information for me to diagnose what's going on (like your version of Zen Cart, the version of USU ...).

It's really best to report these types of issues on USU's Zen Cart support thread: https://www.zen-cart.com/showthread.php?199064 so that other users can "chime in" on the interoperation.

I'll note, however, that the current versions (v3.0.0 and later) of USU rely _totally_ on notifications coming from the Zen Cart `zen_href_link` function for its link-generation.

**Comment by dtomlins** [comment]
Good Morning!

I'll add a couple things here about 'Dynamic Filter' which I use here, and is why I dropped USU215
Just installed 302, and it has the similar problem.
Here or in Zen?  I thought the fix 23 would solve this, but I was wrong (again :) )

WITHOUT usu, this is a valid URL:
https://www.beadfx.com/catalogue/index.php?main_page=index&cPath=20_10_131&sort=20a&fltColor[]=Orange&fltColor[]=Green

WITH usu, the url  (ignoring green yet) is modified to:
https://www.beadfx.com/catalogue/swarovski-bicones-c-20_10_131/?sort=20a&fltColor%5B%5D=Orange

Clicking on green to "add" it, the orange gets dropped  (doesn't recognize a "get array" ) and changes to:
https://www.beadfx.com/catalogue/swarovski-bicones-c-20_10_131/?sort=20a&fltColor%5B%5D=Green

I'm looking for where that "valid" character(s) get re-mapped.

Dan

**Comment by lat9** [comment]
Ugh!  `$_GET` parameters that are arrays?  That is, as you guessed, the source of the issue that you're having, as those arrays are probably getting squished by the `usu::parse_parameters` method's processing.

I'll take a look over the next week, but I'm not promising anything.  There are _many_ locations in the Zen Cart base processing that will throw a 'hair-ball' when presented with a `$_GET` array ... I've seen many such logs when a PCI scanner does its bit.

**Comment by dtomlins** [comment]
Yup - that looks like where.  I'll have a look too.

Meanwhile in includes/classes/usu.php  function href_link

//dmt        $generated_url = htmlspecialchars($link, ENT_QUOTES, CHARSET, false);
        $generated_url = str_replace(array("%5B", "%5D"), array("[", "]"), htmlspecialchars($link, ENT_QUOTES | ENT_HTML401, CHARSET, false) );

restores the []  so it Dynamic Filters works, but I'll look at the compression so that multi-select works.

Dan

**Comment by qingyangge** [comment]
you can check my site https://www.legerbabe.com

**Comment by qingyangge** [comment]
zencart v1.5.6c and usu 3.0.2

**Comment by dtomlins** [comment]
> you can check my site https://www.legerbabe.com

I see the same issue with filters sort-of.  Except it is passing "Array" instead of values, so they don't filter.  Change the filter style in Dynamic Filter from Multi, and it should work.
But this isn't Cindy's (lat9) problem :D

**Comment by dtomlins** [comment]
Hi Cindy
In addition to my restoring %5B and %5D above see below
I can send the whole file if you'd prefer.  This appears to solve, but not likely the prettiest!

Dan

A few changes to function parse_parameters.  All are added lines  tagged   //dmt

        $this->log('Parsing Parameters for ' . $page);
        $this->log(var_export($p, true));

        $container = array();
        $container_of_arrays = '';                                                                      //dmt
        foreach ($p as $index => $valuepair){
            $p2 = @explode('=', $valuepair);

...
               case 'id':    // EZ-Pages
                    switch (true) {
                        case ($page == FILENAME_EZPAGES):
                            $url = $this->make_url($page, $this->get_ezpages_name($p2[1]), $p2[0], $p2[1], USU_END, $separator);
                            break;
                        default:
                            $container[$p2[0]] = $p2[1];
                            break;
                        }
                    break;

                default:
                    if(strstr($p2[0],'[]')) { $container_of_arrays .= '&' . $p2[0] . '=' . $p2[1];      //dmt
                        } else {                                                                        //dmt
                    $container[$p2[0]] = $p2[1];
                        }                                                                               //dmt
                    break;
            }
        }

        $url = isset($url) ? $url : $page . USU_END;
        if (sizeof($container) > 0) {
            if ($imploded_params = $this->build_query($container)) {
                $url .= $separator . zen_output_string($imploded_params);
                $separator = '&';
            }
        }

        $url .= $container_of_arrays;                                                                   // dmt

        return $url;

**Comment by lat9** [comment]
Sure, Dan, 'shoot' that file my way (and thanks).

**Comment by dtomlins** [comment]
Here is revised includes/classes/usu.php  which retains Dynamic Filter multiple selection data  /dmt
[usu.php.gz](https://github.com/lat9/usu/files/3801575/usu.php.gz)

**Comment by lat9** [comment]
Thanks, Dan.  I've been fussing with this a bit ... what's your site's setting for **_Configuration->Ultimate URLs->Enable automatic redirects?_**?  If it's set to `false`, does changing it to `true` correct the issue that you're seeing?

**Comment by lat9** [comment]
I _believe_ that the change just pushed _should_ correct those $_GET array-related issues.  Waiting for confirmation before I call it 'fix provided'.

**Comment by dtomlins** [comment]
I call it fixed from my testing 2 live.

Dan

[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "
https://github.com/lat9/usu/issues/27?email_source=notifications\u0026email_token=ALTF43YD2OI2KIT6MPVKHBLQSBZLTA5CNFSM4JIDS66KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDANMTI#issuecomment-549508685
",
"url": "
https://github.com/lat9/usu/issues/27?email_source=notifications\u0026email_token=ALTF43YD2OI2KIT6MPVKHBLQSBZLTA5CNFSM4JIDS66KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDANMTI#issuecomment-549508685
",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
