### ISSUE TITLE
Faulty query causes failures

### ISSUE THREAD

**Issue by lat9** [lat9/usu#31]
As reported by @webchills in #30 

There is a faulty query in the current includes/classes/usu.php around line 1240:
```
if (USU_FORMAT == 'parent' || USU_CATEGORY_DIR == 'short') { $sql = "SELECT c.categories_id AS id, c.parent_id, cd.categories_name AS cName, cd2.categories_name as pName FROM " . TABLE_CATEGORIES . " AS c, " . TABLE_CATEGORIES_DESCRIPTION . " AS cd LEFT JOIN " . TABLE_CATEGORIES_DESCRIPTION . " AS cd2 ON c.parent_id = cd2.categories_id AND cd2.language_id = {$this->languages_id} WHERE c.categories_id = cd.categories_id AND cd.language_id = {$this->languages_id}"; } else { $sql = "SELECT categories_id AS id, categories_name AS cName FROM " . TABLE_CATEGORIES_DESCRIPTION . " WHERE language_id = {$this->languages_id}"; }
```
Using MySQL 5.6 and PHP 7.3.6 and Zen Cart 1.5.6 the first query fails with:
```
PHP Fatal error: 1054:Unknown column 'c.parent_id' in 'on clause' :: SELECT c.categories_id AS id, c.parent_id, cd.categories_name AS cName, cd2.categories_name as pName FROM categories AS c, categories_description AS cd LEFT JOIN categories_description AS cd2 ON c.parent_id = cd2.categories_id AND cd2.language_id = 1 WHERE c.categories_id = cd.categories_id AND cd.language_id = 1 ==> (as called by) /xxx/xxx/includes/classes/usu.php on line 1255
```
which prevents the whole admin from loading

**Comment by lat9** [comment]
Cr@p, that's what I get for messing and 'assuming' ordering.

**Comment by lat9** [comment]
@webchills, there's the update; let me know if you agree that the issue's corrected and I'll get v3.0.4 released.

**Comment by webchills** [comment]
Yup this has fixed it.
Before you release 3.0.4 I would change line 201 again from
`if ($connection == 'SSL' && ENABLE_SSL == 'true') {`
to
`if ($connection == 'SSL' && ENABLE_SSL_CATALOG == 'true') {`
to prevent PHP 7.3 warning logs
This change got lost in a previous update

**Comment by lat9** [comment]
Thanks, again, @webchills.  I'll get that updated as well.

**Comment by lat9** [comment]
... and there it is.  I'll get v3.0.4 going ...
