### ISSUE TITLE
code suggestion....

### ISSUE THREAD

**Issue by proseLA** [lat9/usu#36]
https://github.com/lat9/usu/blob/a2956e63e44b393edd9a63d7b6c2c328932c0e1e/includes/classes/usu.php#L1017

hi cindy, 
i have some clients that store html in the categories name.  i'm not sure if others do as well, but i think this code would be better (at least for me), if this line was:

```
$retval = strip_tags($string);
```

i know if would make my life easier....

thoughts?

**Comment by lat9** [comment]
I'll buy that, since the two existing filters (punctuation and non-alphabetical) would simply remove the unwanted characters, leaving `<h1>` as `h1` ... which is probably not desirable.

**Comment by lat9** [comment]
FWIW, I'll plan to use the Zen Cart `zen_clean_html` function to get CR/LR/TAB characters out as well.

I also noted that the `switch` statement a couple of lines down in the `filter` method has the `default` first, which doesn't feel right to me, so I'm changing that too as part of this issue.

**Comment by proseLA** [comment]
the `zen_clean_html` has the potential to leave beginning and/or ending white space.  any chance we could do a `trim(zen_clean_html($string))`?

(feel free to call me so demanding now...)

**Comment by lat9** [comment]
Done (and thanks).

**Comment by proseLA** [comment]
thanks for all you do!
