### ISSUE TITLE
refactoring suggestion...

### ISSUE THREAD

**Issue by proseLA** [lat9/usu#37]
hi again!
i would think not re-using the name ```pName``` for multiple uses would make this code more legible; at least for me.

there is the var ```$pName``` which refers to the product name and then there are times when in sql you are using it to refer to either the parent category name or the product name.  see:

https://github.com/lat9/usu/blob/a2956e63e44b393edd9a63d7b6c2c328932c0e1e/includes/classes/usu.php#L1254

and 

https://github.com/lat9/usu/blob/a2956e63e44b393edd9a63d7b6c2c328932c0e1e/includes/classes/usu.php#L597

having different names would make it a bit easier for me to debug; as rarely does anything work straight out of the box for me.  in updating this plugin, i only needed to make 3 changes that i can tell.  which is awesome!  i still need to do more testing though...

**Comment by lat9** [comment]
Since your previous request requires change to this class-file, I'll bite on this one, too; otherwise, I'd consider this a low-priority change.

**Comment by proseLA** [comment]
as long as you are biting, it seems that there is a bunch of duplicate code in the functions, ```generate_products_cache```, ```get_product_canonical```, and ```get_product_name```.  seems that the sql is all rather similar (its early and i'm rushing to get out).  is there a reason it is broken out like that?  and is there a reason we have chosen not to use the ```zen_get_products_name``` function?  (oh, i wish there was a product class!)  sorry if a little thread drift, but i think the issues are similar.

**Comment by lat9** [comment]
Noting that the duplicate code you've identified was 'inherited'; I'll look into doing some combining.

**Comment by lat9** [comment]
Noting also the use of an uninitialized variable (`$categories_clause`) in the `get_product_canonical` method which will result in, at a minimum, a PHP notice.

**Comment by lat9** [comment]
Removing the `get_parent_categories_id` method, as it's exactly the same processing as `zen_get_parent_categories`.

**Comment by lat9** [comment]
> 
> 
> Noting that the duplicate code you've identified was 'inherited'; I'll look into doing some combining.

That's going to be a PITA to combine, since the 'after-processing' in each of those methods is slightly different and depends on the database-query's result.

**Comment by proseLA** [comment]
isn't refactoring always a bit of PITA?

for the `get_product_name` function, could we not just simply use the `zen_get_products_name` name here:

https://github.com/lat9/usu/blob/068e13eb54e3a70539027cd59e09cd00954e6d21/includes/classes/usu.php#L615

i would think that could work on the other 2.

i'm sure there is also a `zen_` function to retrieve the master cat ID as well.

while i agree that the after processing is slightly different; there db queries could easily be combined into a separate protected function or make use the zen functions.

just my 2c; free of charge.

in addition, i'm not sure about the canonical (nor do i think most store owners understand it, as i barely do).  if i look here:

https://github.com/lat9/usu/blob/068e13eb54e3a70539027cd59e09cd00954e6d21/includes/classes/usu.php#L682

and then here:

https://github.com/lat9/usu/blob/068e13eb54e3a70539027cd59e09cd00954e6d21/includes/classes/usu.php#L719

that strikes me as the potential to have a canonical link with 2 category names despite the content of the page being exactly the same.  is that the intention of a canonical link?  please correct me if i'm wrong, but i thought the canonical link was the link used by search engines to index a page, so that if there was multiple URLs to get to the same page, search engines would only use the canonical, and you therefore would not get penalized for duplicate content.

am i wrong in that?

ok, maybe that's 4c.

**Comment by lat9** [comment]
@proseLA, how's that looking?

**Comment by proseLA** [comment]
@lat9 give me a couple of days, and i will have something for you to look at.  no worries.

best.

**Comment by lat9** [comment]
Unfortunately, running a test (demo products on zc155f, although the zen cart version isn't an issue) I've found discrepancies between the original (using 3.0.6) and the update's generated URLs.  These are all using Hardware :: Printers (there's only the one).  The two links after each combination reflect the v3.0.6 vs. v3.0.7 link-generation.

I've added a `(X)` to the link that appears to be incorrect; looks like the v3.0.7 update has corrected
- auto / parent /short
- auto / original / off

... but needs an update for
- off / parent / short
- off / original / off

```
Generate cPath / format of alt urls / display cats as directories

auto / parent /short    
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html  (X)
    http://localhost/zc155fusu/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
off / parent / short    
    http://localhost/zc155fusu/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/hardware-printers-c-1_5/big-linked-hewlett-packard-laserjet-1100xi-linked-p-27.html   (X)
off / original / short  
    http://localhost/zc155fusu/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
auto / original / short 
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
auto / original / full  
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
auto / parent / full    
    n/a
auto / parent / off     
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html?cPath=1_5
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html?cPath=1_5
auto / original / off   
    http://localhost/zc155fusu/big-linked-hewlett-packard-laserjet-1100xi-linked-p-27.html?cPath=1_5  (X)
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html?cPath=1_5
off / original / off   
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/big-linked-hewlett-packard-laserjet-1100xi-linked-p-27.html  (X)
off / original / full
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html
off / parent / full
    n/a
off / parent / off
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html
    http://localhost/zc155fusu/hewlett-packard-laserjet-1100xi-linked-p-27.html
```

I'll note that the little exercise in checking those generated links points out that there's 'overlap' of the generated URLs for many of the combinations!  That could lead to a more simple configuration for a future release.

**Comment by proseLA** [comment]
i will examine...

**Comment by proseLA** [comment]
i will look closer later.  i am NOT able to reproduce the described errors with my changes (3.07):

off / parent / short
https://zc157.com/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html

off / original / off
https://zc157.com/hewlett-packard-laserjet-1100xi-linked-p-27.html

i'm running 157 commit a22cbcc9cef43047ac  which is somewhere between b and c.  (it seems chris is now stamping files ahead of release as i see 1.5.7c in headers).

can you please reverify?  i will reload my testdata if necessary.  entirely possible that my testdata is not as it was.

the issue is with the big-linked.  and i see the printer as being linked to another category.

**Comment by lat9** [comment]
Hmm, some core-file change between zc155f (which I was using) and zc157?  Sweet!

**Comment by proseLA** [comment]
yeah, i am not able to reproduce the error as described.  i can reload my testdata although that will have to wait for now.  

the `zen_get_products_name` function has not changed.  i am not sure how any of my code would get the `big-linked` into the url...  does not mean it does not... i'm just not seeing it.

i will reload testdata later.  if not today, tomorrow...

here is what that product looks like:

![image](https://user-images.githubusercontent.com/1095136/103372443-eac84a80-4a86-11eb-86ce-937b837be647.png)

**Comment by proseLA** [comment]
cindy,
just so we are clear, we are talking about the product links when clicking through.  we are NOT talking about the canonical link that is part of the `<head>`.  right?

thanks.

**Comment by proseLA** [comment]
i loaded fresh data.  still can not reproduce the error. 

settings: off / parent / short 

if i click through the big linked category, i come to this URL:
https://zc157.com/big-linked-c-22/hewlett-packard-laserjet-1100xi-linked-p-27.html

which has a canonical of:
https://zc157.com/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html

that link has the same canonical as itself (which is good and correct, IMO).

if i come through hardware and then printer, i get:

https://zc157.com/hardware-printers-c-1_5/hewlett-packard-laserjet-1100xi-linked-p-27.html

which is the same canonical.

off / original / off:
https://zc157.com/hewlett-packard-laserjet-1100xi-linked-p-27.html

not sure how you are getting that big-linked in the name with my code changes.

**Comment by lat9** [comment]
After retesting, I'm not seeing that 'big-linked' added to the generated URLs, either.  Apologies, it must have been something in the USU cache (I was toggling back and forth between the new and old class).  For my updated testing, I've disabled the USU cache globally so that I'm sure I'm seeing what I 'should be' seeing.

**Comment by lat9** [comment]
Teeny update just posted, converting those 'naughty' tabs to 4 spaces.

**Comment by proseLA** [comment]
> Teeny update just posted, converting those 'naughty' tabs to 4 spaces.

from the PR:
> 
> (ps i hope i did not screw up the formatting too bad!)

all good!
