### ISSUE TITLE
necessary refactor for php8

### ISSUE THREAD

**Issue by proseLA** [lat9/usu#39]
https://github.com/lat9/usu/blob/a2956e63e44b393edd9a63d7b6c2c328932c0e1e/includes/classes/usu.php#L560

one can not have a required paramater following an optional parameter.  all optional parameters must be last in the parm string.

**Comment by lat9** [comment]
Thanks for that, @proseLA!

**Comment by lat9** [comment]
Hmm, that `$separator` variable isn't even used by that method!

**Comment by proseLA** [comment]
i did not even look at that.
