### ISSUE TITLE
Missing `zen_product_in_parent_category` for admin processing

### ISSUE THREAD

**Issue by lat9** [lat9/usu#41]
As reported in [this](https://www.zen-cart.com/showthread.php?199064-Ultimate-SEO-v3-(and-v2-200)-Support-Thread&p=1376849#post1376849) Zen Cart support-thread posting.  The issue was introduced in USU v3.0.7.

**Comment by proseLA** [comment]
hi cindy,
this is a bug that looks to be corrected in v158.  the function is currently only available on the catalog side.  in v158, it looks to be loaded on the admin side as well:
```
includes/init_includes/init_general_funcs.php:24:require DIR_WS_FUNCTIONS . 'functions_categories.php';
admin/includes/init_includes/init_general_funcs.php:30:require DIR_FS_CATALOG . DIR_WS_FUNCTIONS . 'functions_categories.php';
```

it would be nice if we could just load the whole catalog categories script, but unfortunately there are duplicate function names.  

one way to solve might be to do something like:

https://github.com/lat9/usu/blob/62e5ed8a29d3fb8a89505df64dadc4a9d5db4dcb/YOUR_ADMIN/includes/functions/extra_functions/usu.php#L58-L94

**Comment by lat9** [comment]
Thanks, @proseLA.  I'll get that going over the next couple of days.

**Comment by lat9** [comment]
Darn, my testing didn't show this up because I was testing USU with Edit Orders and EO already has overrides for the two functions.  Since it's loaded first, everything was available for USU's use.

**Comment by proseLA** [comment]
probably what happened to me as well!
