### ISSUE TITLE
Old URLs aren't rewriting to new ones

### ISSUE THREAD

**Issue by lat9** [lat9/usu#43]
Thanks lat9.

One problem is, old urls aren't rewriting to new ones. For example if originally my product was named and available at https://www.koolbadges.co.uk/japanese-doll-badges-p-3121.html but after being renamed is now at https://www.koolbadges.co.uk/cute-blue-japanese-doll-badges-p-3121.html with the rewrite I would expect the old url to redirect to the new to reflect the name change, however both urls are returning a 200 response and are valid. 

**Note**: Updated to provide the full link names (were previously truncated).

_Originally posted by @jodsclass in https://github.com/lat9/usu/issues/42#issuecomment-822206239_

**Comment by lat9** [comment]
Noting that the canonical link for both of those product links is `https://www.koolbadges.co.uk/cute-blue-japanese-doll-badges-p-3121.html`.  What settings were changed to 'rename' those product links?

**Comment by jodsclass** [comment]
Products which have been renamed in the admin section such as renaming a product from a plural with an (s) to a singular, such as changing a product name “product name badges” to “product name badge”. I was thinking that a url made up of the old product name would 301 to the url composed of the new name. Also meaning any links to the old products elsewhere will pass some of that link credit to the new updated url via the 301. 

Thanks
John J. Large
MSc, BSc, PGc, PGd
Computer scientist and privacy researcher. 
https://www.johnlarge.co.uk

**Comment by jodsclass** [comment]
Just tested further, if I manually enter a url in the old format such as 

https://www.koolbadges.co.uk/index.php?main_page=product_info&products_id=904

It now doesn't redirect with the beta to the SEO url. That will return a 200 response. The rewritten url is https://www.koolbadges.co.uk/camo-pink-badges-p-904.html?cPath=9 so the 301 automatic rewrites now don't seem to be working.

**Comment by jodsclass** [comment]
Just reverted to 3.0.8 and the redirects work as I mentioned, redirecting any changes in the url to the canonical, so the automatic rewrites appear to have been broken by the changes in the beta. So by fixing the redirect loop on deleted products it seems to have broken the automatic rewrites on valid products

**Comment by lat9** [comment]
Thanks for the testing, @jodsclass.  I'll close this issue as the unwanted operations are a direct result of the changes posted for #42.

**Comment by lat9** [comment]
I'm (obviously) having a bad USU-day.  In reviewing the admin-side handling which is 'supposed to' reset the various USU caches on changes to products, categories, manufacturers and EZ-Pages, I see that the logic is flawed.

The admin-side USU initialization script is looking for accesses to the appropriate (albeit missing `product_music` and the other product-type variants) change to an element that might be cached, but that base operation (e.g. changing a product's name) hasn't taken effect when USU's admin observer instantiates the base USU class.  That class' constructor then rebuilds the cache, using the current (and no longer valid) entries.

**Comment by jodsclass** [comment]
Oh no. It would seem like I've opened the proverbial 'can of worms' with my initial bug report. Hope it's not too much to fix.
