### ISSUE TITLE
break out of while loop

### ISSUE THREAD

**Issue by proseLA** [lat9/usu#45]
https://github.com/lat9/usu/blob/2adeec5f0132ba0c25b29a4c91e6c8a4060ca28f/YOUR_ADMIN/includes/functions/extra_functions/usu.php#L68-L71

this function has potential for processing savings.  once `$in_cat` is set to true, could we not break out of the while loop?

it seems it could also be done around line 83 with an else statement as well (would need 2 breaks; could potentially do another if to prevent reading of the next parent category as well):

https://github.com/lat9/usu/blob/2adeec5f0132ba0c25b29a4c91e6c8a4060ca28f/YOUR_ADMIN/includes/functions/extra_functions/usu.php#L78-L84

or am i wrong here?

**Comment by lat9** [comment]
I agree with your assessment, but note that the `zen_product_in_category` function is provided if-and-only-if that function's not already present (i.e. the base Zen Cart version is < zc157) and the code for that function is essentially that present in zc157c.

How about a PR to the Zen Cart base instead?

**Comment by proseLA** [comment]
i had not noticed that there!  i noticed it on edit_orders....

i agree, i'll take a look over at the ZC base.

best.

**Comment by proseLA** [comment]
done.  and merged.

**Comment by lat9** [comment]
Thanks, @proseLA!
